pub mod assign;
pub mod batch;
pub mod candidate;
pub mod chemistry;
pub mod dna;
pub mod ec_index;
pub mod fastq;
pub mod gtf;
pub mod index;
pub mod index_build;
pub mod lookup;
pub mod metrics;
pub mod minimizer;
pub mod read_store;
pub mod score;
pub mod score_scalar;
pub mod score_simd;
pub mod simulate;
pub mod sketch;
pub mod transcriptome_target;

pub type ReadId = u64;
pub type GeneId = u32;
pub type TranscriptId = u32;
